//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_TOURDL.Models
{
    using DAPM_TOURDL.Patterns.Prototype;
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN:IPrototype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.SPTOURs = new HashSet<SPTOUR>();
            ID_NV = 1;
            HoTen_NV = "Nguyễn Văn A";
            GioiTinh_NV = "Nam";
            NgaySinh_NV = DateTime.Now;
            MatKhau = "1234567";
            Mail_NV = "nguyenvana@gmail.com";
            ChucVu = "Admin";
            SDT_NV = "0123456789";
        }
        
        public NHANVIEN(NHANVIEN nv)
        {
            ID_NV = nv.ID_NV;
            HoTen_NV = nv.HoTen_NV;
            GioiTinh_NV = nv.GioiTinh_NV;
            NgaySinh_NV = nv.NgaySinh_NV;
            MatKhau = nv.MatKhau;
            Mail_NV = nv.Mail_NV;
            ChucVu = nv.ChucVu;
            SDT_NV = nv.SDT_NV;
        }

        public int ID_NV { get; set; }
        public string HoTen_NV { get; set; }
        public string GioiTinh_NV { get; set; }
        public System.DateTime NgaySinh_NV { get; set; }
        public string MatKhau { get; set; }
        public string Mail_NV { get; set; }
        public string ChucVu { get; set; }
        public string SDT_NV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPTOUR> SPTOURs { get; set; }

        public IPrototype Clone()
        {
            return new NHANVIEN(this);
        }
    }
}
